import type { Metadata } from "next";
import { UserData } from "./types/user";

import { Nunito } from "next/font/google";
import { ClerkProvider, auth } from "@clerk/nextjs";

import "./globals.css";
import Sidebar from "./Components/Sidebar/Sidebar";
import GlobalStyleProvider from "./providers/GlobalStyleProvider";
import ContextProvider from "./providers/ContextProvider";
import NextTopLoader from "nextjs-toploader";
import StyledComponentsRegistry from './registry'
import AdminSidebar from "./Components/AdminSidebar/AdminSidebar";
import AdminLayout from "./Layouts/AdminLayout";
import UserLayout from "./Layouts/UserLayout";

const nunito = Nunito({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();

  const userData: UserData = {
    userId,
    userRole: "Admin", // This should come from your authentication system
    phoneNumber: "1111111111",
    password: "Qwerty@123",
    stage: "Initial",
    isActive: true,
  }
  const renderLayout = () => {
    if (!userId) {
      return (
        <div className="w-full">
          {children}
        </div>
      );
    }

    return userData.userRole === 'Admin' ? (
      <AdminLayout>{children}</AdminLayout>
    ) : (
      <UserLayout>{children}</UserLayout>
    );
  }
  


  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
            integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        </head>
        <body className={nunito.className}>
          <NextTopLoader
            height={2}
            color="#27AE60"
            easing="cubic-bezier(0.53,0.21,0,1)"
          />
          <StyledComponentsRegistry>
            <ContextProvider>
              {/* <GlobalStyleProvider> */}
              {renderLayout()}
              {/* </GlobalStyleProvider> */}
            </ContextProvider>
          </StyledComponentsRegistry>
        </body>
      </html>
   </ClerkProvider>
  );
}
